services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        - internal-network
            
  productsapi:
    image: productsapi
    build:
      context: .
      dockerfile: ProductsAPI/Dockerfile
    networks:
        - internal-network


  customerapigw:
    image: customerapigw
    build:
      context: .
      dockerfile: CustomerAPIGW/Dockerfile
    networks:
        - internal-network


  ordersapigw:
    image: ordersapigw
    build:
      context: .
      dockerfile: OrdersAPIGW/Dockerfile
    networks:
        - internal-network


  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    networks:
        - internal-network


  ordersapi:
    image: ordersapi
    build:
      context: .
      dockerfile: OrdersAPI/Dockerfile
    networks:
        - internal-network


  baseapigw:
    image: baseapigw
    build:
      context: .
      dockerfile: BaseAPIGW/Dockerfile
    ports:
        - "5000:80"
    networks:
        - internal-network
        
  authenticationapi:
      image: authenticationapi
      build:
        context: .
        dockerfile: AuthenticationApi/Dockerfile
      networks:
          - internal-network
networks:
  internal-network:
    driver: bridge

