services:
  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  cartapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  productsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

